apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: avahi-reflector
  namespace: print
spec:
  selector:
    matchLabels:
      app: avahi-reflector
  template:
    metadata:
      labels:
        app: avahi-reflector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: storagenodet3500.vmstation.local
      containers:
        - name: avahi
          image: ydkn/avahi:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: REFLECTOR_ENABLE_REFLECTOR
              value: "yes"
          volumeMounts:
            - name: airprint-service
              mountPath: /etc/avahi/services/airprint.service
              subPath: airprint.service
      volumes:
        - name: airprint-service
          configMap:
            name: avahi-airprint-config