apiVersion: v1
kind: Service
metadata:
  name: paperless-nodeport
  namespace: print
spec:
  selector:
    app: paperless
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 31000
      protocol: TCP
