---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
data:
  use-forwarded-headers: "true"
  proxy-body-size: "0"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
