all:
  children:
    linux_nodes:
      children:
        control_plane:
          hosts:
            masternode:
              ansible_host: 192.168.4.63
              ansible_connection: local
              ansible_user: jjbly
              wol_mac: "00:e0:4c:68:cb:bf"
        workers:
          hosts:
            storagenodet3500:
              ansible_host: 192.168.4.61
              ansible_user: jjbly
              ansible_ssh_private_key_file: ~/.ssh/id_ed25519
              wol_mac: "b8:ac:6f:7e:6c:9d"
    windows_nodes:
      hosts:
        homelab:
          ansible_host: 192.168.4.62
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_user: svc-ansible
          ansible_password: "{{ vault_windows_ansible_password }}"
          wol_mac: "d0:94:66:30:d6:63"
