apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: vaultwarden/server
    newTag: "1.32.7"
