---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/lib/vaultwarden
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - masternode.vmstation.local
